const actionTypes = {
  // USER
  RESET_USER: "RESET_USER",
  UPDATE_USER: "UPDATE_USER",
  // ADMINISTRATOR
  RESET_ADMINISTRATOR: "RESET_ADMINISTRATOR",
  UPDATE_ADMINISTRATOR: "UPDATE_ADMINISTRATOR",
  // EDIT_INFO
  RESET_EDIT_INFO: "RESET_EDIT_INFO",
  UPDATE_EDIT_INFO: "UPDATE_EDIT_INFO",
  // UPYUN
  RESET_UPYUN: "RESET_UPYUN",
  // FLATTENED_NODE
  RESET_FLATTENED_NODE: "RESET_FLATTENED_NODE",
  UPDATE_FLATTENED_NODE: "UPDATE_FLATTENED_NODE",
  UPDATE_FLATTENED_NODES: "UPDATE_FLATTENED_NODES",
  ADD_FLATTENED_NODE: "ADD_FLATTENED_NODE",
  ADD_FLATTENED_NODES: "ADD_FLATTENED_NODES",
  REMOVE_FLATTENED_NODE: "REMOVE_FLATTENED_NODE",
  REMOVE_FLATTENED_NODES: "REMOVE_FLATTENED_NODES",
  // 混合处理
  MIXED_PROCESSING_FLATTENED_NODES: "MIXED_PROCESSING_FLATTENED_NODES",
};

export default actionTypes;